### ISSUE TITLE
Make performance datasets choice more flexible

### ISSUE THREAD

**Issue by HealthyPear** [cta-observatory/iact-estimator#2]
Right now it is all based on MAGIC data since the original script was developed there

if we want to add support for other instruments (e.g. LST) or a combination of instruments the configuration file section should be more flexible allowing us to choose an instrument and zenith range (observation time is already there)

```yaml
instrument: MAGIC
zenith_range: mid
observation_time: 50 h
```
Any specific choice will point to a specific dataset which should be described in the documentation.
